Line 50 should be False instead of True
If we use True, it would be re-learning stage. However, when we first time training with the yaml, it will raise an error showed as below:

ValueError: snapshot ./experiments/checkpoints/cityscapes_2task/warmup_model.pth.tar does not exist